#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prototype_SEP_Team3
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="team3")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMonHocLINQ(MonHocLINQ instance);
    partial void UpdateMonHocLINQ(MonHocLINQ instance);
    partial void DeleteMonHocLINQ(MonHocLINQ instance);
    partial void InsertMonTienQuyetLINQ(MonTienQuyetLINQ instance);
    partial void UpdateMonTienQuyetLINQ(MonTienQuyetLINQ instance);
    partial void DeleteMonTienQuyetLINQ(MonTienQuyetLINQ instance);
    partial void InsertTaiKhoanLINQ(TaiKhoanLINQ instance);
    partial void UpdateTaiKhoanLINQ(TaiKhoanLINQ instance);
    partial void DeleteTaiKhoanLINQ(TaiKhoanLINQ instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Prototype_SEP_Team3.Properties.Settings.Default.team3ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<MonHocLINQ> MonHocLINQs
		{
			get
			{
				return this.GetTable<MonHocLINQ>();
			}
		}
		
		public System.Data.Linq.Table<MonTienQuyetLINQ> MonTienQuyetLINQs
		{
			get
			{
				return this.GetTable<MonTienQuyetLINQ>();
			}
		}
		
		public System.Data.Linq.Table<TaiKhoanLINQ> TaiKhoanLINQs
		{
			get
			{
				return this.GetTable<TaiKhoanLINQ>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_MONTIENQUYET_GET")]
		public ISingleResult<SP_MONTIENQUYET_GETResult> SP_MONTIENQUYET_GET([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> ctdt, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> hk, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ctdt, hk, id);
			return ((ISingleResult<SP_MONTIENQUYET_GETResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MonHoc")]
	public partial class MonHocLINQ : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Id;
		
		private int _ChuongTrinhDaoTao_Id;
		
		private string _TenMonHoc;
		
		private string _TenTiengAnh;
		
		private System.Nullable<int> _LoaiKienThuc;
		
		private System.Nullable<int> _SoTinChi;
		
		private System.Nullable<int> _HocKy;
		
		private System.Nullable<int> _GiangVienPhuTrach_Id;
		
		private string _NoiDungVanTat;
		
		private System.Nullable<int> _SoGioLyThuyet;
		
		private System.Nullable<int> _SoGioThucHanh;
		
		private EntitySet<MonTienQuyetLINQ> _MonTienQuyets;
		
		private EntitySet<MonTienQuyetLINQ> _MonTienQuyets1;
		
		private EntityRef<TaiKhoanLINQ> _TaiKhoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(string value);
    partial void OnIdChanged();
    partial void OnChuongTrinhDaoTao_IdChanging(int value);
    partial void OnChuongTrinhDaoTao_IdChanged();
    partial void OnTenMonHocChanging(string value);
    partial void OnTenMonHocChanged();
    partial void OnTenTiengAnhChanging(string value);
    partial void OnTenTiengAnhChanged();
    partial void OnLoaiKienThucChanging(System.Nullable<int> value);
    partial void OnLoaiKienThucChanged();
    partial void OnSoTinChiChanging(System.Nullable<int> value);
    partial void OnSoTinChiChanged();
    partial void OnHocKyChanging(System.Nullable<int> value);
    partial void OnHocKyChanged();
    partial void OnGiangVienPhuTrach_IdChanging(System.Nullable<int> value);
    partial void OnGiangVienPhuTrach_IdChanged();
    partial void OnNoiDungVanTatChanging(string value);
    partial void OnNoiDungVanTatChanged();
    partial void OnSoGioLyThuyetChanging(System.Nullable<int> value);
    partial void OnSoGioLyThuyetChanged();
    partial void OnSoGioThucHanhChanging(System.Nullable<int> value);
    partial void OnSoGioThucHanhChanged();
    #endregion
		
		public MonHocLINQ()
		{
			this._MonTienQuyets = new EntitySet<MonTienQuyetLINQ>(new Action<MonTienQuyetLINQ>(this.attach_MonTienQuyets), new Action<MonTienQuyetLINQ>(this.detach_MonTienQuyets));
			this._MonTienQuyets1 = new EntitySet<MonTienQuyetLINQ>(new Action<MonTienQuyetLINQ>(this.attach_MonTienQuyets1), new Action<MonTienQuyetLINQ>(this.detach_MonTienQuyets1));
			this._TaiKhoan = default(EntityRef<TaiKhoanLINQ>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChuongTrinhDaoTao_Id", DbType="Int NOT NULL")]
		public int ChuongTrinhDaoTao_Id
		{
			get
			{
				return this._ChuongTrinhDaoTao_Id;
			}
			set
			{
				if ((this._ChuongTrinhDaoTao_Id != value))
				{
					this.OnChuongTrinhDaoTao_IdChanging(value);
					this.SendPropertyChanging();
					this._ChuongTrinhDaoTao_Id = value;
					this.SendPropertyChanged("ChuongTrinhDaoTao_Id");
					this.OnChuongTrinhDaoTao_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMonHoc", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenMonHoc
		{
			get
			{
				return this._TenMonHoc;
			}
			set
			{
				if ((this._TenMonHoc != value))
				{
					this.OnTenMonHocChanging(value);
					this.SendPropertyChanging();
					this._TenMonHoc = value;
					this.SendPropertyChanged("TenMonHoc");
					this.OnTenMonHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTiengAnh", DbType="VarChar(100)")]
		public string TenTiengAnh
		{
			get
			{
				return this._TenTiengAnh;
			}
			set
			{
				if ((this._TenTiengAnh != value))
				{
					this.OnTenTiengAnhChanging(value);
					this.SendPropertyChanging();
					this._TenTiengAnh = value;
					this.SendPropertyChanged("TenTiengAnh");
					this.OnTenTiengAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiKienThuc", DbType="Int")]
		public System.Nullable<int> LoaiKienThuc
		{
			get
			{
				return this._LoaiKienThuc;
			}
			set
			{
				if ((this._LoaiKienThuc != value))
				{
					this.OnLoaiKienThucChanging(value);
					this.SendPropertyChanging();
					this._LoaiKienThuc = value;
					this.SendPropertyChanged("LoaiKienThuc");
					this.OnLoaiKienThucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTinChi", DbType="Int")]
		public System.Nullable<int> SoTinChi
		{
			get
			{
				return this._SoTinChi;
			}
			set
			{
				if ((this._SoTinChi != value))
				{
					this.OnSoTinChiChanging(value);
					this.SendPropertyChanging();
					this._SoTinChi = value;
					this.SendPropertyChanged("SoTinChi");
					this.OnSoTinChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HocKy", DbType="Int")]
		public System.Nullable<int> HocKy
		{
			get
			{
				return this._HocKy;
			}
			set
			{
				if ((this._HocKy != value))
				{
					this.OnHocKyChanging(value);
					this.SendPropertyChanging();
					this._HocKy = value;
					this.SendPropertyChanged("HocKy");
					this.OnHocKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiangVienPhuTrach_Id", DbType="Int")]
		public System.Nullable<int> GiangVienPhuTrach_Id
		{
			get
			{
				return this._GiangVienPhuTrach_Id;
			}
			set
			{
				if ((this._GiangVienPhuTrach_Id != value))
				{
					if (this._TaiKhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnGiangVienPhuTrach_IdChanging(value);
					this.SendPropertyChanging();
					this._GiangVienPhuTrach_Id = value;
					this.SendPropertyChanged("GiangVienPhuTrach_Id");
					this.OnGiangVienPhuTrach_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDungVanTat", DbType="NVarChar(500)")]
		public string NoiDungVanTat
		{
			get
			{
				return this._NoiDungVanTat;
			}
			set
			{
				if ((this._NoiDungVanTat != value))
				{
					this.OnNoiDungVanTatChanging(value);
					this.SendPropertyChanging();
					this._NoiDungVanTat = value;
					this.SendPropertyChanged("NoiDungVanTat");
					this.OnNoiDungVanTatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoGioLyThuyet", DbType="Int")]
		public System.Nullable<int> SoGioLyThuyet
		{
			get
			{
				return this._SoGioLyThuyet;
			}
			set
			{
				if ((this._SoGioLyThuyet != value))
				{
					this.OnSoGioLyThuyetChanging(value);
					this.SendPropertyChanging();
					this._SoGioLyThuyet = value;
					this.SendPropertyChanged("SoGioLyThuyet");
					this.OnSoGioLyThuyetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoGioThucHanh", DbType="Int")]
		public System.Nullable<int> SoGioThucHanh
		{
			get
			{
				return this._SoGioThucHanh;
			}
			set
			{
				if ((this._SoGioThucHanh != value))
				{
					this.OnSoGioThucHanhChanging(value);
					this.SendPropertyChanging();
					this._SoGioThucHanh = value;
					this.SendPropertyChanged("SoGioThucHanh");
					this.OnSoGioThucHanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MonHoc_MonTienQuyet", Storage="_MonTienQuyets", ThisKey="Id", OtherKey="Monhoc_Id")]
		public EntitySet<MonTienQuyetLINQ> MonTienQuyets
		{
			get
			{
				return this._MonTienQuyets;
			}
			set
			{
				this._MonTienQuyets.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MonHoc_MonTienQuyet1", Storage="_MonTienQuyets1", ThisKey="Id", OtherKey="Montienquyet_Id")]
		public EntitySet<MonTienQuyetLINQ> MonTienQuyetLINQs
		{
			get
			{
				return this._MonTienQuyets1;
			}
			set
			{
				this._MonTienQuyets1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_MonHoc", Storage="_TaiKhoan", ThisKey="GiangVienPhuTrach_Id", OtherKey="Id", IsForeignKey=true)]
		public TaiKhoanLINQ TaiKhoanLINQ
		{
			get
			{
				return this._TaiKhoan.Entity;
			}
			set
			{
				TaiKhoanLINQ previousValue = this._TaiKhoan.Entity;
				if (((previousValue != value) 
							|| (this._TaiKhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TaiKhoan.Entity = null;
						previousValue.MonHocLINQs.Remove(this);
					}
					this._TaiKhoan.Entity = value;
					if ((value != null))
					{
						value.MonHocLINQs.Add(this);
						this._GiangVienPhuTrach_Id = value.Id;
					}
					else
					{
						this._GiangVienPhuTrach_Id = default(Nullable<int>);
					}
					this.SendPropertyChanged("TaiKhoanLINQ");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MonTienQuyets(MonTienQuyetLINQ entity)
		{
			this.SendPropertyChanging();
			entity.MonHoc = this;
		}
		
		private void detach_MonTienQuyets(MonTienQuyetLINQ entity)
		{
			this.SendPropertyChanging();
			entity.MonHoc = null;
		}
		
		private void attach_MonTienQuyets1(MonTienQuyetLINQ entity)
		{
			this.SendPropertyChanging();
			entity.MonHocLINQ = this;
		}
		
		private void detach_MonTienQuyets1(MonTienQuyetLINQ entity)
		{
			this.SendPropertyChanging();
			entity.MonHocLINQ = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MonTienQuyet")]
	public partial class MonTienQuyetLINQ : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Monhoc_Id;
		
		private string _Montienquyet_Id;
		
		private bool _Status;
		
		private EntityRef<MonHocLINQ> _MonHoc;
		
		private EntityRef<MonHocLINQ> _MonHoc1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnMonhoc_IdChanging(string value);
    partial void OnMonhoc_IdChanged();
    partial void OnMontienquyet_IdChanging(string value);
    partial void OnMontienquyet_IdChanged();
    partial void OnStatusChanging(bool value);
    partial void OnStatusChanged();
    #endregion
		
		public MonTienQuyetLINQ()
		{
			this._MonHoc = default(EntityRef<MonHocLINQ>);
			this._MonHoc1 = default(EntityRef<MonHocLINQ>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Monhoc_Id", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Monhoc_Id
		{
			get
			{
				return this._Monhoc_Id;
			}
			set
			{
				if ((this._Monhoc_Id != value))
				{
					if (this._MonHoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMonhoc_IdChanging(value);
					this.SendPropertyChanging();
					this._Monhoc_Id = value;
					this.SendPropertyChanged("Monhoc_Id");
					this.OnMonhoc_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Montienquyet_Id", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Montienquyet_Id
		{
			get
			{
				return this._Montienquyet_Id;
			}
			set
			{
				if ((this._Montienquyet_Id != value))
				{
					if (this._MonHoc1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMontienquyet_IdChanging(value);
					this.SendPropertyChanging();
					this._Montienquyet_Id = value;
					this.SendPropertyChanged("Montienquyet_Id");
					this.OnMontienquyet_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit NOT NULL")]
		public bool Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MonHoc_MonTienQuyet", Storage="_MonHoc", ThisKey="Monhoc_Id", OtherKey="Id", IsForeignKey=true)]
		public MonHocLINQ MonHoc
		{
			get
			{
				return this._MonHoc.Entity;
			}
			set
			{
				MonHocLINQ previousValue = this._MonHoc.Entity;
				if (((previousValue != value) 
							|| (this._MonHoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MonHoc.Entity = null;
						previousValue.MonTienQuyets.Remove(this);
					}
					this._MonHoc.Entity = value;
					if ((value != null))
					{
						value.MonTienQuyets.Add(this);
						this._Monhoc_Id = value.Id;
					}
					else
					{
						this._Monhoc_Id = default(string);
					}
					this.SendPropertyChanged("MonHoc");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MonHoc_MonTienQuyet1", Storage="_MonHoc1", ThisKey="Montienquyet_Id", OtherKey="Id", IsForeignKey=true)]
		public MonHocLINQ MonHocLINQ
		{
			get
			{
				return this._MonHoc1.Entity;
			}
			set
			{
				MonHocLINQ previousValue = this._MonHoc1.Entity;
				if (((previousValue != value) 
							|| (this._MonHoc1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MonHoc1.Entity = null;
						previousValue.MonTienQuyetLINQs.Remove(this);
					}
					this._MonHoc1.Entity = value;
					if ((value != null))
					{
						value.MonTienQuyetLINQs.Add(this);
						this._Montienquyet_Id = value.Id;
					}
					else
					{
						this._Montienquyet_Id = default(string);
					}
					this.SendPropertyChanged("MonHocLINQ");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoan")]
	public partial class TaiKhoanLINQ : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Email;
		
		private string _Ten;
		
		private string _MatKhau;
		
		private EntitySet<MonHocLINQ> _MonHocs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnTenChanging(string value);
    partial void OnTenChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    #endregion
		
		public TaiKhoanLINQ()
		{
			this._MonHocs = new EntitySet<MonHocLINQ>(new Action<MonHocLINQ>(this.attach_MonHocs), new Action<MonHocLINQ>(this.detach_MonHocs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this.OnTenChanging(value);
					this.SendPropertyChanging();
					this._Ten = value;
					this.SendPropertyChanged("Ten");
					this.OnTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_MonHoc", Storage="_MonHocs", ThisKey="Id", OtherKey="GiangVienPhuTrach_Id")]
		public EntitySet<MonHocLINQ> MonHocLINQs
		{
			get
			{
				return this._MonHocs;
			}
			set
			{
				this._MonHocs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MonHocs(MonHocLINQ entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoanLINQ = this;
		}
		
		private void detach_MonHocs(MonHocLINQ entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoanLINQ = null;
		}
	}
	
	public partial class SP_MONTIENQUYET_GETResult
	{
		
		private string _Id;
		
		private string _TenMonHoc;
		
		private string _TenTiengAnh;
		
		private string _Ten;
		
		public SP_MONTIENQUYET_GETResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMonHoc", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenMonHoc
		{
			get
			{
				return this._TenMonHoc;
			}
			set
			{
				if ((this._TenMonHoc != value))
				{
					this._TenMonHoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTiengAnh", DbType="VarChar(100)")]
		public string TenTiengAnh
		{
			get
			{
				return this._TenTiengAnh;
			}
			set
			{
				if ((this._TenTiengAnh != value))
				{
					this._TenTiengAnh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this._Ten = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
