//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prototype_SEP_Team3
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeCuongChiTiet
    {
        public DeCuongChiTiet()
        {
            this.ChuanDauRaMonHocs = new HashSet<ChuanDauRaMonHoc>();
            this.KeHoachGDHTCuThes = new HashSet<KeHoachGDHTCuThe>();
            this.KeHoanKiemTras = new HashSet<KeHoanKiemTra>();
            this.MucTieuMonHocs = new HashSet<MucTieuMonHoc>();
            this.PPDanhGiaKQHTs = new HashSet<PPDanhGiaKQHT>();
            this.TaiLieuMonHocs = new HashSet<TaiLieuMonHoc>();
        }
    
        public int Id { get; set; }
        public string TenDCCT { get; set; }
        public string TenTiengAnh { get; set; }
        public string MonHoc_Id { get; set; }
        public string TrinhDo { get; set; }
        public string PhanBoThoiGian { get; set; }
        public int MonTienQuyet_Id { get; set; }
        public string YeuCauMonHoc { get; set; }
        public int GiangVienPhuTrach_Id { get; set; }
        public Nullable<int> KhoiKienThuc { get; set; }
        public string GiangVienGiangDay { get; set; }
    
        public virtual ICollection<ChuanDauRaMonHoc> ChuanDauRaMonHocs { get; set; }
        public virtual MonHoc MonHoc { get; set; }
        public virtual MonHoc MonHoc1 { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
        public virtual ICollection<KeHoachGDHTCuThe> KeHoachGDHTCuThes { get; set; }
        public virtual ICollection<KeHoanKiemTra> KeHoanKiemTras { get; set; }
        public virtual ICollection<MucTieuMonHoc> MucTieuMonHocs { get; set; }
        public virtual ICollection<PPDanhGiaKQHT> PPDanhGiaKQHTs { get; set; }
        public virtual ICollection<TaiLieuMonHoc> TaiLieuMonHocs { get; set; }
    }
}
