//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prototype_SEP_Team3
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeCuongChiTiet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeCuongChiTiet()
        {
            this.ChuanDauRaMonHocs = new HashSet<ChuanDauRaMonHoc>();
            this.GVGDs = new HashSet<GVGD>();
            this.KeHoachGDHTCuThes = new HashSet<KeHoachGDHTCuThe>();
            this.KeHoanKiemTras = new HashSet<KeHoanKiemTra>();
            this.MaTran_CDRMH_CDRCTDT = new HashSet<MaTran_CDRMH_CDRCTDT>();
            this.MucTieuMonHocs = new HashSet<MucTieuMonHoc>();
            this.PPDanhGiaKQHTs = new HashSet<PPDanhGiaKQHT>();
            this.TaiLieuMonHocs = new HashSet<TaiLieuMonHoc>();
        }
    
        public int Id { get; set; }
        public string TenDCCT { get; set; }
        public string TenTiengAnh { get; set; }
        public Nullable<int> MonHoc_Id { get; set; }
        public string TrinhDo { get; set; }
        public string PhanBoThoiGian { get; set; }
        public Nullable<int> MonTienQuyet_Id { get; set; }
        public string YeuCauMonHoc { get; set; }
        public string GiangVienPhuTrach { get; set; }
        public Nullable<int> KhoiKienThuc { get; set; }
        public Nullable<bool> Finish { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChuanDauRaMonHoc> ChuanDauRaMonHocs { get; set; }
        public virtual MonHoc MonHoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GVGD> GVGDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KeHoachGDHTCuThe> KeHoachGDHTCuThes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KeHoanKiemTra> KeHoanKiemTras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaTran_CDRMH_CDRCTDT> MaTran_CDRMH_CDRCTDT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MucTieuMonHoc> MucTieuMonHocs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PPDanhGiaKQHT> PPDanhGiaKQHTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaiLieuMonHoc> TaiLieuMonHocs { get; set; }
    }
}
