//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prototype_SEP_Team3
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeHoachGDHTCuThe
    {
        public int Id { get; set; }
        public int DeCuongChiTiet_Id { get; set; }
        public Nullable<int> Tuan { get; set; }
        public Nullable<int> Buoi { get; set; }
        public Nullable<int> LyThuyet { get; set; }
        public Nullable<int> ThaoLuan { get; set; }
        public Nullable<int> BaiTap { get; set; }
        public Nullable<int> TuHoc { get; set; }
        public string Noidung { get; set; }
    
        public virtual DeCuongChiTiet DeCuongChiTiet { get; set; }
    }
}
