//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prototype_SEP_Team3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChuanDauRaMonHoc> ChuanDauRaMonHocs { get; set; }
        public virtual DbSet<ChuongTrinhDaoTao> ChuongTrinhDaoTaos { get; set; }
        public virtual DbSet<DeCuongChiTiet> DeCuongChiTiets { get; set; }
        public virtual DbSet<GiangVienGiangDay> GiangVienGiangDays { get; set; }
        public virtual DbSet<KeHoachGDHTCuThe> KeHoachGDHTCuThes { get; set; }
        public virtual DbSet<KeHoanKiemTra> KeHoanKiemTras { get; set; }
        public virtual DbSet<MaTran_CDRMH_CDRCTDT> MaTran_CDRMH_CDRCTDT { get; set; }
        public virtual DbSet<MaTran_ChuanDauRaMH_HDGDPPDG> MaTran_ChuanDauRaMH_HDGDPPDG { get; set; }
        public virtual DbSet<MonHoc> MonHocs { get; set; }
        public virtual DbSet<MonTienQuyet> MonTienQuyets { get; set; }
        public virtual DbSet<MucTieuDaoTao> MucTieuDaoTaos { get; set; }
        public virtual DbSet<MucTieuMonHoc> MucTieuMonHocs { get; set; }
        public virtual DbSet<PhanQuyenTaiKhoan> PhanQuyenTaiKhoans { get; set; }
        public virtual DbSet<PPDanhGiaKQHT> PPDanhGiaKQHTs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<TaiLieuMonHoc> TaiLieuMonHocs { get; set; }
        public virtual DbSet<ThongTinChung_CTDT> ThongTinChung_CTDT { get; set; }
    
        public virtual int DetailedSyllabus_deleteDetailedSyllabus_ChuanDauRaMonHoc_Sang(Nullable<int> deCuongChiTiet_Id, string noiDung)
        {
            var deCuongChiTiet_IdParameter = deCuongChiTiet_Id.HasValue ?
                new ObjectParameter("DeCuongChiTiet_Id", deCuongChiTiet_Id) :
                new ObjectParameter("DeCuongChiTiet_Id", typeof(int));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DetailedSyllabus_deleteDetailedSyllabus_ChuanDauRaMonHoc_Sang", deCuongChiTiet_IdParameter, noiDungParameter);
        }
    
        public virtual int DetailedSyllabus_updateDetailedSyllabus_ChuanDauRaMonHoc_Sang(Nullable<int> deCuongChiTiet_Id, Nullable<int> sTT, string noiDung)
        {
            var deCuongChiTiet_IdParameter = deCuongChiTiet_Id.HasValue ?
                new ObjectParameter("DeCuongChiTiet_Id", deCuongChiTiet_Id) :
                new ObjectParameter("DeCuongChiTiet_Id", typeof(int));
    
            var sTTParameter = sTT.HasValue ?
                new ObjectParameter("STT", sTT) :
                new ObjectParameter("STT", typeof(int));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DetailedSyllabus_updateDetailedSyllabus_ChuanDauRaMonHoc_Sang", deCuongChiTiet_IdParameter, sTTParameter, noiDungParameter);
        }
    
        public virtual int DetailedSyllabus_updateDetailedSyllabus_ChuanDauRaMonHoc_Thinh(Nullable<int> deCuongChiTiet_Id, Nullable<int> sTT, string noiDung)
        {
            var deCuongChiTiet_IdParameter = deCuongChiTiet_Id.HasValue ?
                new ObjectParameter("DeCuongChiTiet_Id", deCuongChiTiet_Id) :
                new ObjectParameter("DeCuongChiTiet_Id", typeof(int));
    
            var sTTParameter = sTT.HasValue ?
                new ObjectParameter("STT", sTT) :
                new ObjectParameter("STT", typeof(int));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DetailedSyllabus_updateDetailedSyllabus_ChuanDauRaMonHoc_Thinh", deCuongChiTiet_IdParameter, sTTParameter, noiDungParameter);
        }
    
        public virtual int DetailedSyllabus_updateDetailedSyllabus_DeCuongChiTiet_Thinh(Nullable<int> id, string tenDCCT, string tenTiengAnh, string trinhDo, string phanBoThoiGian, string yeuCauMonHoc, Nullable<int> khoiKienThuc, string giangVienPhuTrach)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var tenDCCTParameter = tenDCCT != null ?
                new ObjectParameter("TenDCCT", tenDCCT) :
                new ObjectParameter("TenDCCT", typeof(string));
    
            var tenTiengAnhParameter = tenTiengAnh != null ?
                new ObjectParameter("TenTiengAnh", tenTiengAnh) :
                new ObjectParameter("TenTiengAnh", typeof(string));
    
            var trinhDoParameter = trinhDo != null ?
                new ObjectParameter("TrinhDo", trinhDo) :
                new ObjectParameter("TrinhDo", typeof(string));
    
            var phanBoThoiGianParameter = phanBoThoiGian != null ?
                new ObjectParameter("PhanBoThoiGian", phanBoThoiGian) :
                new ObjectParameter("PhanBoThoiGian", typeof(string));
    
            var yeuCauMonHocParameter = yeuCauMonHoc != null ?
                new ObjectParameter("YeuCauMonHoc", yeuCauMonHoc) :
                new ObjectParameter("YeuCauMonHoc", typeof(string));
    
            var khoiKienThucParameter = khoiKienThuc.HasValue ?
                new ObjectParameter("KhoiKienThuc", khoiKienThuc) :
                new ObjectParameter("KhoiKienThuc", typeof(int));
    
            var giangVienPhuTrachParameter = giangVienPhuTrach != null ?
                new ObjectParameter("GiangVienPhuTrach", giangVienPhuTrach) :
                new ObjectParameter("GiangVienPhuTrach", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DetailedSyllabus_updateDetailedSyllabus_DeCuongChiTiet_Thinh", idParameter, tenDCCTParameter, tenTiengAnhParameter, trinhDoParameter, phanBoThoiGianParameter, yeuCauMonHocParameter, khoiKienThucParameter, giangVienPhuTrachParameter);
        }
    
        public virtual int DetailedSyllabus_updateDetailedSyllabus_KeHoanKiemTra_Thinh(Nullable<int> deCuongChiTiet_Id, string hinhThuc, string noiDung, string thoiDiem, string congCuKT)
        {
            var deCuongChiTiet_IdParameter = deCuongChiTiet_Id.HasValue ?
                new ObjectParameter("DeCuongChiTiet_Id", deCuongChiTiet_Id) :
                new ObjectParameter("DeCuongChiTiet_Id", typeof(int));
    
            var hinhThucParameter = hinhThuc != null ?
                new ObjectParameter("HinhThuc", hinhThuc) :
                new ObjectParameter("HinhThuc", typeof(string));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            var thoiDiemParameter = thoiDiem != null ?
                new ObjectParameter("ThoiDiem", thoiDiem) :
                new ObjectParameter("ThoiDiem", typeof(string));
    
            var congCuKTParameter = congCuKT != null ?
                new ObjectParameter("CongCuKT", congCuKT) :
                new ObjectParameter("CongCuKT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DetailedSyllabus_updateDetailedSyllabus_KeHoanKiemTra_Thinh", deCuongChiTiet_IdParameter, hinhThucParameter, noiDungParameter, thoiDiemParameter, congCuKTParameter);
        }
    
        public virtual int DetailedSyllabus_updateDetailedSyllabus_MaTran_CDRMH_CDRCTDT_Thinh(Nullable<int> chuanDauRaMonHoc_Id, Nullable<int> mucTieuDaoTao_Id, Nullable<bool> status)
        {
            var chuanDauRaMonHoc_IdParameter = chuanDauRaMonHoc_Id.HasValue ?
                new ObjectParameter("ChuanDauRaMonHoc_Id", chuanDauRaMonHoc_Id) :
                new ObjectParameter("ChuanDauRaMonHoc_Id", typeof(int));
    
            var mucTieuDaoTao_IdParameter = mucTieuDaoTao_Id.HasValue ?
                new ObjectParameter("MucTieuDaoTao_Id", mucTieuDaoTao_Id) :
                new ObjectParameter("MucTieuDaoTao_Id", typeof(int));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DetailedSyllabus_updateDetailedSyllabus_MaTran_CDRMH_CDRCTDT_Thinh", chuanDauRaMonHoc_IdParameter, mucTieuDaoTao_IdParameter, statusParameter);
        }
    
        public virtual int DetailedSyllabus_updateDetailedSyllabus_MaTran_ChuanDauRaMH_HDGDPPDG_Thinh(Nullable<int> chuanDauRaMonHoc_Id, string phuongPhapDanhGia, string hoatDongDanhGia, Nullable<int> sTT)
        {
            var chuanDauRaMonHoc_IdParameter = chuanDauRaMonHoc_Id.HasValue ?
                new ObjectParameter("ChuanDauRaMonHoc_Id", chuanDauRaMonHoc_Id) :
                new ObjectParameter("ChuanDauRaMonHoc_Id", typeof(int));
    
            var phuongPhapDanhGiaParameter = phuongPhapDanhGia != null ?
                new ObjectParameter("PhuongPhapDanhGia", phuongPhapDanhGia) :
                new ObjectParameter("PhuongPhapDanhGia", typeof(string));
    
            var hoatDongDanhGiaParameter = hoatDongDanhGia != null ?
                new ObjectParameter("HoatDongDanhGia", hoatDongDanhGia) :
                new ObjectParameter("HoatDongDanhGia", typeof(string));
    
            var sTTParameter = sTT.HasValue ?
                new ObjectParameter("STT", sTT) :
                new ObjectParameter("STT", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DetailedSyllabus_updateDetailedSyllabus_MaTran_ChuanDauRaMH_HDGDPPDG_Thinh", chuanDauRaMonHoc_IdParameter, phuongPhapDanhGiaParameter, hoatDongDanhGiaParameter, sTTParameter);
        }
    
        public virtual int DetailedSyllabus_updateDetailedSyllabus_MonHoc_Thinh(Nullable<int> monHoc_Id_Bang, string monHoc_id)
        {
            var monHoc_Id_BangParameter = monHoc_Id_Bang.HasValue ?
                new ObjectParameter("MonHoc_Id_Bang", monHoc_Id_Bang) :
                new ObjectParameter("MonHoc_Id_Bang", typeof(int));
    
            var monHoc_idParameter = monHoc_id != null ?
                new ObjectParameter("MonHoc_id", monHoc_id) :
                new ObjectParameter("MonHoc_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DetailedSyllabus_updateDetailedSyllabus_MonHoc_Thinh", monHoc_Id_BangParameter, monHoc_idParameter);
        }
    
        public virtual int DetailedSyllabus_updateDetailedSyllabus_MucTieuMonHoc_Thinh(Nullable<int> deCuongChiTiet_Id, string loai, string noiDung, Nullable<int> sTT)
        {
            var deCuongChiTiet_IdParameter = deCuongChiTiet_Id.HasValue ?
                new ObjectParameter("DeCuongChiTiet_Id", deCuongChiTiet_Id) :
                new ObjectParameter("DeCuongChiTiet_Id", typeof(int));
    
            var loaiParameter = loai != null ?
                new ObjectParameter("Loai", loai) :
                new ObjectParameter("Loai", typeof(string));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            var sTTParameter = sTT.HasValue ?
                new ObjectParameter("STT", sTT) :
                new ObjectParameter("STT", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DetailedSyllabus_updateDetailedSyllabus_MucTieuMonHoc_Thinh", deCuongChiTiet_IdParameter, loaiParameter, noiDungParameter, sTTParameter);
        }
    
        public virtual int DetailedSyllabus_updateDetailedSyllabus_PPDanhGia_Thinh(Nullable<int> deCuongChiTiet_Id, string loaiNoiDung, string soLanDanhGia, string trongSo, string hinhThucDanhGia)
        {
            var deCuongChiTiet_IdParameter = deCuongChiTiet_Id.HasValue ?
                new ObjectParameter("DeCuongChiTiet_Id", deCuongChiTiet_Id) :
                new ObjectParameter("DeCuongChiTiet_Id", typeof(int));
    
            var loaiNoiDungParameter = loaiNoiDung != null ?
                new ObjectParameter("LoaiNoiDung", loaiNoiDung) :
                new ObjectParameter("LoaiNoiDung", typeof(string));
    
            var soLanDanhGiaParameter = soLanDanhGia != null ?
                new ObjectParameter("SoLanDanhGia", soLanDanhGia) :
                new ObjectParameter("SoLanDanhGia", typeof(string));
    
            var trongSoParameter = trongSo != null ?
                new ObjectParameter("TrongSo", trongSo) :
                new ObjectParameter("TrongSo", typeof(string));
    
            var hinhThucDanhGiaParameter = hinhThucDanhGia != null ?
                new ObjectParameter("HinhThucDanhGia", hinhThucDanhGia) :
                new ObjectParameter("HinhThucDanhGia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DetailedSyllabus_updateDetailedSyllabus_PPDanhGia_Thinh", deCuongChiTiet_IdParameter, loaiNoiDungParameter, soLanDanhGiaParameter, trongSoParameter, hinhThucDanhGiaParameter);
        }
    
        public virtual int DetailedSyllabus_updateDetailedSyllabus_TaiLieuMonHoc_Thinh(Nullable<int> deCuongChiTiet_Id, string loai, string noiDung, Nullable<int> sTT)
        {
            var deCuongChiTiet_IdParameter = deCuongChiTiet_Id.HasValue ?
                new ObjectParameter("DeCuongChiTiet_Id", deCuongChiTiet_Id) :
                new ObjectParameter("DeCuongChiTiet_Id", typeof(int));
    
            var loaiParameter = loai != null ?
                new ObjectParameter("Loai", loai) :
                new ObjectParameter("Loai", typeof(string));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            var sTTParameter = sTT.HasValue ?
                new ObjectParameter("STT", sTT) :
                new ObjectParameter("STT", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DetailedSyllabus_updateDetailedSyllabus_TaiLieuMonHoc_Thinh", deCuongChiTiet_IdParameter, loaiParameter, noiDungParameter, sTTParameter);
        }
    
        public virtual int DetailedSyllabus_updateSTTDetailedSyllabus_ChuanDauRaMonHoc_Sang(Nullable<int> deCuongChiTiet_Id, Nullable<int> sTT, string noiDung)
        {
            var deCuongChiTiet_IdParameter = deCuongChiTiet_Id.HasValue ?
                new ObjectParameter("DeCuongChiTiet_Id", deCuongChiTiet_Id) :
                new ObjectParameter("DeCuongChiTiet_Id", typeof(int));
    
            var sTTParameter = sTT.HasValue ?
                new ObjectParameter("STT", sTT) :
                new ObjectParameter("STT", typeof(int));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DetailedSyllabus_updateSTTDetailedSyllabus_ChuanDauRaMonHoc_Sang", deCuongChiTiet_IdParameter, sTTParameter, noiDungParameter);
        }
    
        public virtual int Load_DCCT_Thinh(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Load_DCCT_Thinh", idParameter);
        }
    
        public virtual ObjectResult<Load_KeHoachKiemTra_Thinh_Result> Load_KeHoachKiemTra_Thinh(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Load_KeHoachKiemTra_Thinh_Result>("Load_KeHoachKiemTra_Thinh", idParameter);
        }
    
        public virtual ObjectResult<Load_KetHoachGiangDay_MonHoc_Thinh_Result> Load_KetHoachGiangDay_MonHoc_Thinh(Nullable<int> id, Nullable<int> hocKi)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var hocKiParameter = hocKi.HasValue ?
                new ObjectParameter("HocKi", hocKi) :
                new ObjectParameter("HocKi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Load_KetHoachGiangDay_MonHoc_Thinh_Result>("Load_KetHoachGiangDay_MonHoc_Thinh", idParameter, hocKiParameter);
        }
    
        public virtual ObjectResult<string> Load_LoaiTaiLieu_Thinh()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Load_LoaiTaiLieu_Thinh");
        }
    
        public virtual ObjectResult<Load_MaTran_ChuanDauRaMH_HDGDPPDG_Thinh_Result> Load_MaTran_ChuanDauRaMH_HDGDPPDG_Thinh(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Load_MaTran_ChuanDauRaMH_HDGDPPDG_Thinh_Result>("Load_MaTran_ChuanDauRaMH_HDGDPPDG_Thinh", idParameter);
        }
    
        public virtual ObjectResult<Load_MucTieuMonHoc_Thinh_Result> Load_MucTieuMonHoc_Thinh(Nullable<int> id, string loai)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var loaiParameter = loai != null ?
                new ObjectParameter("Loai", loai) :
                new ObjectParameter("Loai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Load_MucTieuMonHoc_Thinh_Result>("Load_MucTieuMonHoc_Thinh", idParameter, loaiParameter);
        }
    
        public virtual ObjectResult<Load_PPDanhGia_Thinh_Result> Load_PPDanhGia_Thinh(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Load_PPDanhGia_Thinh_Result>("Load_PPDanhGia_Thinh", idParameter);
        }
    
        public virtual ObjectResult<Load_TaiLieu_MonHoc_Thinh_Result> Load_TaiLieu_MonHoc_Thinh(Nullable<int> id, string loai)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var loaiParameter = loai != null ?
                new ObjectParameter("Loai", loai) :
                new ObjectParameter("Loai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Load_TaiLieu_MonHoc_Thinh_Result>("Load_TaiLieu_MonHoc_Thinh", idParameter, loaiParameter);
        }
    
        public virtual ObjectResult<Load_TaiLieuMonHoc_Thinh_Result> Load_TaiLieuMonHoc_Thinh(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Load_TaiLieuMonHoc_Thinh_Result>("Load_TaiLieuMonHoc_Thinh", idParameter);
        }
    
        public virtual ObjectResult<LoadChuanDauRaCTDTTheoMonHoc_Result> LoadChuanDauRaCTDTTheoMonHoc()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LoadChuanDauRaCTDTTheoMonHoc_Result>("LoadChuanDauRaCTDTTheoMonHoc");
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int SP_MONHOC_DELETE(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MONHOC_DELETE", idParameter);
        }
    
        public virtual ObjectResult<SP_MONHOC_VIEW_Result> SP_MONHOC_VIEW(Nullable<int> ctdt)
        {
            var ctdtParameter = ctdt.HasValue ?
                new ObjectParameter("ctdt", ctdt) :
                new ObjectParameter("ctdt", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MONHOC_VIEW_Result>("SP_MONHOC_VIEW", ctdtParameter);
        }
    
        public virtual int SP_MONTIENQUYET_DEL(Nullable<int> idmonhoc)
        {
            var idmonhocParameter = idmonhoc.HasValue ?
                new ObjectParameter("idmonhoc", idmonhoc) :
                new ObjectParameter("idmonhoc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MONTIENQUYET_DEL", idmonhocParameter);
        }
    
        public virtual ObjectResult<SP_MONTIENQUYET_GET_Result> SP_MONTIENQUYET_GET(Nullable<int> ctdt, Nullable<int> hk, Nullable<int> id)
        {
            var ctdtParameter = ctdt.HasValue ?
                new ObjectParameter("ctdt", ctdt) :
                new ObjectParameter("ctdt", typeof(int));
    
            var hkParameter = hk.HasValue ?
                new ObjectParameter("hk", hk) :
                new ObjectParameter("hk", typeof(int));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MONTIENQUYET_GET_Result>("SP_MONTIENQUYET_GET", ctdtParameter, hkParameter, idParameter);
        }
    
        public virtual ObjectResult<SP_MONTIENQUYET_GETTRUE_Result> SP_MONTIENQUYET_GETTRUE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MONTIENQUYET_GETTRUE_Result>("SP_MONTIENQUYET_GETTRUE");
        }
    
        public virtual int SP_MUCTIEUDAOTAO_DEL(Nullable<int> ctdt)
        {
            var ctdtParameter = ctdt.HasValue ?
                new ObjectParameter("ctdt", ctdt) :
                new ObjectParameter("ctdt", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MUCTIEUDAOTAO_DEL", ctdtParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual ObjectResult<SP_TEXT_Result> SP_TEXT(Nullable<int> idmonhoc)
        {
            var idmonhocParameter = idmonhoc.HasValue ?
                new ObjectParameter("idmonhoc", idmonhoc) :
                new ObjectParameter("idmonhoc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TEXT_Result>("SP_TEXT", idmonhocParameter);
        }
    
        public virtual int SP_THOIGIANDAOTAO_HANDLE(Nullable<int> ctdt, Nullable<double> tgdt)
        {
            var ctdtParameter = ctdt.HasValue ?
                new ObjectParameter("ctdt", ctdt) :
                new ObjectParameter("ctdt", typeof(int));
    
            var tgdtParameter = tgdt.HasValue ?
                new ObjectParameter("tgdt", tgdt) :
                new ObjectParameter("tgdt", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_THOIGIANDAOTAO_HANDLE", ctdtParameter, tgdtParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
