//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prototype_SEP_Team3
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanQuyenTaiKhoan
    {
        public int TaiKhoan_Id { get; set; }
        public string TenPhanQuyen { get; set; }
        public bool EditCTDT { get; set; }
        public bool EditDCCT { get; set; }
        public bool ViewCTDT { get; set; }
        public bool ViewDCCT { get; set; }
        public bool CreateCTDT { get; set; }
        public bool CreateDCCT { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
